apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\BIN\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: php-host
  name: php-host
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php-host
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\BIN\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: php-host
    spec:
      containers:
      - image: kdvel/dof-php:latest
        imagePullPolicy: ""
        name: php-host
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /site
          name: web-site
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: web-site
        hostPath:
          path: /vagrant/app
          type: Directory
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\BIN\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: php-host
  name: php-host
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    io.kompose.service: php-host
status:
  loadBalancer: {}
